package com.server.db.dao;

import com.server.db.model.ChannelRecord;
import com.server.db.model.ChannelRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int countByExample(ChannelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int deleteByExample(ChannelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int insert(ChannelRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int insertSelective(ChannelRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    List<ChannelRecord> selectByExample(ChannelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    ChannelRecord selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChannelRecord record, @Param("example") ChannelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChannelRecord record, @Param("example") ChannelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChannelRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChannelRecord record);
}