package com.server.db.dao;

import com.server.db.model.ServerRecord;
import com.server.db.model.ServerRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServerRecordMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_servers
     * @mbggenerated
     */
    int countByExample(ServerRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_servers
     * @mbggenerated
     */
    int deleteByExample(ServerRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_servers
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_servers
     * @mbggenerated
     */
    int insert(ServerRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_servers
     * @mbggenerated
     */
    int insertSelective(ServerRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_servers
     * @mbggenerated
     */
    List<ServerRecord> selectByExample(ServerRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_servers
     * @mbggenerated
     */
    ServerRecord selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_servers
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ServerRecord record, @Param("example") ServerRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_servers
     * @mbggenerated
     */
    int updateByExample(@Param("record") ServerRecord record, @Param("example") ServerRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_servers
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ServerRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_servers
     * @mbggenerated
     */
    int updateByPrimaryKey(ServerRecord record);
}