package com.server.db.dao;

import com.server.db.model.UserRecord;
import com.server.db.model.UserRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRecordMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_users
     * @mbggenerated
     */
    int countByExample(UserRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_users
     * @mbggenerated
     */
    int deleteByExample(UserRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_users
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_users
     * @mbggenerated
     */
    int insert(UserRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_users
     * @mbggenerated
     */
    int insertSelective(UserRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_users
     * @mbggenerated
     */
    List<UserRecord> selectByExample(UserRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_users
     * @mbggenerated
     */
    UserRecord selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_users
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserRecord record, @Param("example") UserRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_users
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserRecord record, @Param("example") UserRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_users
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_users
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRecord record);
}