package com.server.db.model;

import java.util.Date;

public class UserRecord {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_users.userId
     * @mbggenerated
     */
    private Long userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_users.sdkCannel
     * @mbggenerated
     */
    private Integer sdkCannel;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_users.sdk_uid
     * @mbggenerated
     */
    private String sdk_uid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_users.channel
     * @mbggenerated
     */
    private String channel;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_users.lastServerId
     * @mbggenerated
     */
    private String lastServerId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_users.loginTimestamp
     * @mbggenerated
     */
    private Date loginTimestamp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_users.createTime
     * @mbggenerated
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_users.device
     * @mbggenerated
     */
    private String device;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_users.deviceVersion
     * @mbggenerated
     */
    private String deviceVersion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_users.loginIP
     * @mbggenerated
     */
    private String loginIP;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_users.userId
     * @return  the value of t_users.userId
     * @mbggenerated
     */
    public Long getUserId() {
	return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_users.userId
     * @param userId  the value for t_users.userId
     * @mbggenerated
     */
    public void setUserId(Long userId) {
	this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_users.sdkCannel
     * @return  the value of t_users.sdkCannel
     * @mbggenerated
     */
    public Integer getSdkCannel() {
	return sdkCannel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_users.sdkCannel
     * @param sdkCannel  the value for t_users.sdkCannel
     * @mbggenerated
     */
    public void setSdkCannel(Integer sdkCannel) {
	this.sdkCannel = sdkCannel;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_users.sdk_uid
     * @return  the value of t_users.sdk_uid
     * @mbggenerated
     */
    public String getSdk_uid() {
	return sdk_uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_users.sdk_uid
     * @param sdk_uid  the value for t_users.sdk_uid
     * @mbggenerated
     */
    public void setSdk_uid(String sdk_uid) {
	this.sdk_uid = sdk_uid == null ? null : sdk_uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_users.channel
     * @return  the value of t_users.channel
     * @mbggenerated
     */
    public String getChannel() {
	return channel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_users.channel
     * @param channel  the value for t_users.channel
     * @mbggenerated
     */
    public void setChannel(String channel) {
	this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_users.lastServerId
     * @return  the value of t_users.lastServerId
     * @mbggenerated
     */
    public String getLastServerId() {
	return lastServerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_users.lastServerId
     * @param lastServerId  the value for t_users.lastServerId
     * @mbggenerated
     */
    public void setLastServerId(String lastServerId) {
	this.lastServerId = lastServerId == null ? null : lastServerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_users.loginTimestamp
     * @return  the value of t_users.loginTimestamp
     * @mbggenerated
     */
    public Date getLoginTimestamp() {
	return loginTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_users.loginTimestamp
     * @param loginTimestamp  the value for t_users.loginTimestamp
     * @mbggenerated
     */
    public void setLoginTimestamp(Date loginTimestamp) {
	this.loginTimestamp = loginTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_users.createTime
     * @return  the value of t_users.createTime
     * @mbggenerated
     */
    public Date getCreateTime() {
	return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_users.createTime
     * @param createTime  the value for t_users.createTime
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
	this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_users.device
     * @return  the value of t_users.device
     * @mbggenerated
     */
    public String getDevice() {
	return device;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_users.device
     * @param device  the value for t_users.device
     * @mbggenerated
     */
    public void setDevice(String device) {
	this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_users.deviceVersion
     * @return  the value of t_users.deviceVersion
     * @mbggenerated
     */
    public String getDeviceVersion() {
	return deviceVersion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_users.deviceVersion
     * @param deviceVersion  the value for t_users.deviceVersion
     * @mbggenerated
     */
    public void setDeviceVersion(String deviceVersion) {
	this.deviceVersion = deviceVersion == null ? null : deviceVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_users.loginIP
     * @return  the value of t_users.loginIP
     * @mbggenerated
     */
    public String getLoginIP() {
	return loginIP;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_users.loginIP
     * @param loginIP  the value for t_users.loginIP
     * @mbggenerated
     */
    public void setLoginIP(String loginIP) {
	this.loginIP = loginIP == null ? null : loginIP.trim();
    }
}